/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.wstorage;

import static java.lang.System.exit;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Podol
 */
public class tela_menu extends javax.swing.JFrame {

    /**
     * Creates new form tela_menu
     */
    public tela_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_centralMenu = new javax.swing.JPanel();
        pn_menuRapido = new javax.swing.JPanel();
        lbl_menuRapido = new javax.swing.JLabel();
        btn_os = new javax.swing.JButton();
        btn_manutencoes = new javax.swing.JButton();
        btn_estoque = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        pn_informação = new javax.swing.JPanel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        menu_informacoes = new javax.swing.JMenuBar();
        menu_configuracao = new javax.swing.JMenu();
        mmi_perfil = new javax.swing.JMenuItem();
        mmi_usuario = new javax.swing.JMenuItem();
        mmi_localizacao = new javax.swing.JMenuItem();
        mmi_manutencao = new javax.swing.JMenuItem();
        mmi_servico = new javax.swing.JMenuItem();
        menu_relatorio = new javax.swing.JMenu();
        menu_cadastro = new javax.swing.JMenu();
        mni_equipamento = new javax.swing.JMenuItem();
        mmi_maquinas = new javax.swing.JMenuItem();
        mni_funcionario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WStorage");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pn_centralMenu.setBackground(new java.awt.Color(255, 255, 255));

        pn_menuRapido.setBackground(new java.awt.Color(32, 107, 165));

        lbl_menuRapido.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbl_menuRapido.setForeground(new java.awt.Color(255, 255, 255));
        lbl_menuRapido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_menuRapido.setText("Menu Rápido");

        btn_os.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_os.setText("Ordem de Serviço");
        btn_os.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_osActionPerformed(evt);
            }
        });

        btn_manutencoes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_manutencoes.setText("Manutenções");
        btn_manutencoes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_manutencoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manutencoesActionPerformed(evt);
            }
        });

        btn_estoque.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_estoque.setText("Estoque");
        btn_estoque.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estoqueActionPerformed(evt);
            }
        });

        btn_sair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_menuRapidoLayout = new javax.swing.GroupLayout(pn_menuRapido);
        pn_menuRapido.setLayout(pn_menuRapidoLayout);
        pn_menuRapidoLayout.setHorizontalGroup(
            pn_menuRapidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_menuRapido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_menuRapidoLayout.createSequentialGroup()
                .addGroup(pn_menuRapidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_menuRapidoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_sair))
                    .addGroup(pn_menuRapidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pn_menuRapidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_manutencoes, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_menuRapidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_os)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_menuRapidoLayout.setVerticalGroup(
            pn_menuRapidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuRapidoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_menuRapido)
                .addGap(38, 38, 38)
                .addComponent(btn_os, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btn_manutencoes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btn_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(btn_sair)
                .addGap(17, 17, 17))
        );

        lbl_usuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_usuario.setText("BEM-VINDO Igor Stein | Cargo: Adiministrador");

        lbl_data.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_data.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbl_dataAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout pn_informaçãoLayout = new javax.swing.GroupLayout(pn_informação);
        pn_informação.setLayout(pn_informaçãoLayout);
        pn_informaçãoLayout.setHorizontalGroup(
            pn_informaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_informaçãoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_data, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_informaçãoLayout.setVerticalGroup(
            pn_informaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_informaçãoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_informaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_data, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_usuario))
                .addContainerGap())
        );

        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Igor Stein\\Desktop\\SystemWStorage\\SystemWStorage\\WStorage\\src\\main\\java\\imagens\\logo_menu.png")); // NOI18N

        javax.swing.GroupLayout pn_centralMenuLayout = new javax.swing.GroupLayout(pn_centralMenu);
        pn_centralMenu.setLayout(pn_centralMenuLayout);
        pn_centralMenuLayout.setHorizontalGroup(
            pn_centralMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_informação, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_centralMenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pn_menuRapido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        pn_centralMenuLayout.setVerticalGroup(
            pn_centralMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_centralMenuLayout.createSequentialGroup()
                .addGroup(pn_centralMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_centralMenuLayout.createSequentialGroup()
                        .addComponent(pn_menuRapido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(pn_centralMenuLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pn_informação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu_informacoes.setBackground(new java.awt.Color(32, 107, 165));
        menu_informacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menu_configuracao.setText("Configuração");
        menu_configuracao.setAutoscrolls(true);
        menu_configuracao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        menu_configuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_configuracaoActionPerformed(evt);
            }
        });

        mmi_perfil.setText("Perfil");
        mmi_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmi_perfilActionPerformed(evt);
            }
        });
        menu_configuracao.add(mmi_perfil);

        mmi_usuario.setText("Usuários");
        mmi_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmi_usuarioActionPerformed(evt);
            }
        });
        menu_configuracao.add(mmi_usuario);

        mmi_localizacao.setText("Localizações");
        mmi_localizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmi_localizacaoActionPerformed(evt);
            }
        });
        menu_configuracao.add(mmi_localizacao);

        mmi_manutencao.setText("Manutenções");
        mmi_manutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmi_manutencaoActionPerformed(evt);
            }
        });
        menu_configuracao.add(mmi_manutencao);

        mmi_servico.setText("Serviços");
        mmi_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmi_servicoActionPerformed(evt);
            }
        });
        menu_configuracao.add(mmi_servico);

        menu_informacoes.add(menu_configuracao);

        menu_relatorio.setText("Relatórios");
        menu_relatorio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        menu_informacoes.add(menu_relatorio);

        menu_cadastro.setText("Cadastro");
        menu_cadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        mni_equipamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mni_equipamento.setText("Equipamentos");
        mni_equipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_equipamentoActionPerformed(evt);
            }
        });
        menu_cadastro.add(mni_equipamento);

        mmi_maquinas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mmi_maquinas.setText("Maquinas");
        mmi_maquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmi_maquinasActionPerformed(evt);
            }
        });
        menu_cadastro.add(mmi_maquinas);

        mni_funcionario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mni_funcionario.setText("Funcionário");
        mni_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_funcionarioActionPerformed(evt);
            }
        });
        menu_cadastro.add(mni_funcionario);

        menu_informacoes.add(menu_cadastro);

        setJMenuBar(menu_informacoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_centralMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_centralMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mmi_maquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmi_maquinasActionPerformed
        tela_menu.this.dispose();
        tela_lista_cadastroMaquinas jMenuItem1_maquinas = new tela_lista_cadastroMaquinas();
        jMenuItem1_maquinas.setVisible(true);
    }//GEN-LAST:event_mmi_maquinasActionPerformed

    private void btn_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estoqueActionPerformed
        tela_menu.this.dispose();
        tela_estoqueEqp btn_estoque = new tela_estoqueEqp();
        btn_estoque.setVisible(true);
    }//GEN-LAST:event_btn_estoqueActionPerformed

    private void btn_osActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_osActionPerformed
        tela_menu.this.dispose();
        tela_lista_cadastroOS btn_os = new tela_lista_cadastroOS();
        btn_os.setVisible(true);
    }//GEN-LAST:event_btn_osActionPerformed

    private void mni_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_funcionarioActionPerformed
        tela_lista_funcionarios mni_funcionario = new tela_lista_funcionarios();
        mni_funcionario.setVisible(true);
    }//GEN-LAST:event_mni_funcionarioActionPerformed

    private void lbl_dataAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbl_dataAncestorAdded
        // Informar data no sistema
        Date dataHoraAtual = new Date();
        String data = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
        lbl_data.setText("DATA: " + data);
    }//GEN-LAST:event_lbl_dataAncestorAdded

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void mmi_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmi_perfilActionPerformed
        tela_perfil M_perfil = new tela_perfil();
        M_perfil.setVisible(true);
    }//GEN-LAST:event_mmi_perfilActionPerformed

    private void mmi_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmi_usuarioActionPerformed
        tela_lista_usuarios M_usuario = new tela_lista_usuarios();
        M_usuario.setVisible(true);
    }//GEN-LAST:event_mmi_usuarioActionPerformed

    private void menu_configuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_configuracaoActionPerformed

    }//GEN-LAST:event_menu_configuracaoActionPerformed

    private void mmi_localizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmi_localizacaoActionPerformed
        tela_localizacao M_localizacao = new tela_localizacao();
        M_localizacao.setVisible(true);
    }//GEN-LAST:event_mmi_localizacaoActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // Fechar o sistema
        exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void mmi_manutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmi_manutencaoActionPerformed
        tela_manutencao m_manutencao = new tela_manutencao();
        m_manutencao.setVisible(true);
    }//GEN-LAST:event_mmi_manutencaoActionPerformed

    private void mmi_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmi_servicoActionPerformed
        tela_servico M_servico = new tela_servico();
        M_servico.setVisible(true);
    }//GEN-LAST:event_mmi_servicoActionPerformed

    private void mni_equipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_equipamentoActionPerformed
        tela_menu.this.dispose();
        tela_lista_cadastroEquipamentos mni_equipamento = new tela_lista_cadastroEquipamentos();
        mni_equipamento.setVisible(true); 
    }//GEN-LAST:event_mni_equipamentoActionPerformed

    private void btn_manutencoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manutencoesActionPerformed
        tela_menu.this.dispose();
        tela_lista_manutencoes btn_manutencoes = new tela_lista_manutencoes();
        btn_manutencoes.setVisible(true);
    }//GEN-LAST:event_btn_manutencoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_estoque;
    private javax.swing.JButton btn_manutencoes;
    private javax.swing.JButton btn_os;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_menuRapido;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JMenu menu_cadastro;
    private javax.swing.JMenu menu_configuracao;
    private javax.swing.JMenuBar menu_informacoes;
    private javax.swing.JMenu menu_relatorio;
    private javax.swing.JMenuItem mmi_localizacao;
    private javax.swing.JMenuItem mmi_manutencao;
    private javax.swing.JMenuItem mmi_maquinas;
    private javax.swing.JMenuItem mmi_perfil;
    private javax.swing.JMenuItem mmi_servico;
    private javax.swing.JMenuItem mmi_usuario;
    private javax.swing.JMenuItem mni_equipamento;
    private javax.swing.JMenuItem mni_funcionario;
    private javax.swing.JPanel pn_centralMenu;
    private javax.swing.JPanel pn_informação;
    private javax.swing.JPanel pn_menuRapido;
    // End of variables declaration//GEN-END:variables
}
